version: "3"

services:

  web:
    image: "acinwinstack/getstartedlab:p80"
    deploy:
      replicas: 5
      restart_policy:
        condition: "on-failure"
      resources:
        limits:
          cpus: "0.1"
          memory: "50M"
    ports: ["80:80"]
    networks: ["webnet"]

  visualizer:
    image: "dockersamples/visualizer:stable"
    deploy:
      placement:
        constraints: [node.role == manager]
    ports: ["8080:8080"]
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    networks: ["webnet"]

  redis:
    image: "redis"
    deploy:
      placement:
        constraints: [node.role == manager]
    ports: ["6379:6379"]
    volumes: ["./data:/data"]
    networks: ["webnet"]

networks:
  webnet:
