version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: acinwinstack/getstartedlab
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "80:1234"
    networks:
      - webnet
networks:
  webnet:
