version: "3"
services:
  web:
    # replace acinwinstack/getstartedlab:p80 with your name and image details
    image: acinwinstack/getstartedlab:p80
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
